services:
  redis:

    image: 'redis:alpine'
    volumes:
      - 'redis:/data'
    env_file:
      - ./project.env
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping']
  sql:

    build: ./sql
    volumes:
      - capstone-sql:/var/lib/postgresql/data/
    env_file:
      - ./project.env
  backend:
    build: backend
    env_file:
      - project.env
    user: 'node'
    volumes:
      - ./backend/src:/home/node/app/src
volumes:
  capstone-sql:
    driver: local
  redis:
    driver: local